#!/bin/bash

set -e
#set -x

function copy_install_to_desktop() {
  if [ $# -ne 4 ]; then
    return;
  fi
  local curFileName=$1
  local aiDesktopName=$2
  local curUserName=$3
  local initSetup=$4
  if [ -e "${APP_DATA}/${aiDesktopName}" ]; then
    cp -f ${APP_DATA}/${aiDesktopName} "${curFileName}/${gDesktopName}/"
    if test $? -eq 0; then
      chmod +x "${curFileName}/${gDesktopName}/${aiDesktopName}"
      chown ${curUserName} "${curFileName}/${gDesktopName}/${aiDesktopName}"
      # update init setup info
      mkdir -p $(dirname ${initSetup})
      echo ${gDesktopName} >> ${initSetup}
    fi
  fi
}

aiDesktop=(
  "object-detection.desktop"
  #"hand-tracker.desktop"
  "pose-tracker.desktop"
)
function config_desktop() {
  gDesktopName="桌面"
  if [ -d "/root/桌面" ]; then
    gDesktopName="桌面"
  elif [ -d "/root/Desktop" ]; then
    gDesktopName="Desktop"
  fi

  for FILENAME in /home/*; do

    if [ -f "${FILENAME}/.config/user-dirs.dirs" ]; then
      if [ ! $HOME ]; then HOME=${FILENAME}; fi
      # Import user dir config
      source "${FILENAME}/.config/user-dirs.dirs"
      if [ ! -d "${XDG_DESKTOP_DIR}" ]; then
        mkdir -p "${XDG_DESKTOP_DIR}" >/dev/null 2>&1 || true
      fi
      # Replace(Remove) "${HOME}/" by "" in ${XDG_DESKTOP_DIR} with greedy mode
      gDesktopName="${XDG_DESKTOP_DIR//${HOME}\//}"
    else
      if [ -d "${FILENAME}/桌面" ]; then
        gDesktopName="桌面"
      elif [ -d "${FILENAME}/Desktop" ]; then
        gDesktopName="Desktop"
      fi
    fi

    if [ -d "${FILENAME}/${gDesktopName}" ]; then
      local curUserName=$(echo ${FILENAME} | awk '{print substr($FILENAME, 7, 32)}')
      for desktop in "${aiDesktop[@]}"; do
        local initSetup="${FILENAME}/.config/${APP_NAME}/applications/${desktop%.desktop}-initial-setup-done"
        if [ -f ${initSetup} ] && [ "$(cat ${initSetup} | grep ${gDesktopName})" ]; then
          continue # desktop is already configured
        fi
        copy_install_to_desktop ${FILENAME} ${desktop} ${curUserName} ${initSetup}
      done
    fi
  done
}

## ------------------------- ##

function postinst_init() {
  export APP_NAME=bianbu-ai-support
  export APP_DATA=/usr/share/applications
}

function postinst_configure() {
  config_desktop
}

function postinst_triggered() {
  for triggername in $1; do
    case "$triggername" in
    *)
      echo "unhandled/unknown trigger!" $triggername
      exit 1
      ;;
    esac
  done
}

function postinst_main() {
  if [ $# -eq 0 ]; then
    return;
  fi

  postinst_init
  case $1 in
    configure )   shift; postinst_configure $@;;
    triggered )   shift; postinst_triggered $@;;
  esac
}

args="$@"
postinst_main $@
